[tool.poetry]
name = "banking-api"
version = "0.0.0"
description = "A simple banking API built with FastAPI and Python 3"
authors = ["Breno Filgueiras <breno.fil.costa@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.32.0"}
pydantic = {extras = ["email"], version = "^2.9.2"}
python-multipart = "^0.0.12"
docling = "^2.85.0"
loguru = "^0.7.3"
pikepdf = "^9.4.2"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"